//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoTecnology.WebVentas.servicioImpresionPedido {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaDocumento", Namespace="http://schemas.datacontract.org/2004/07/ServicioImpresion")]
    [System.SerializableAttribute()]
    public partial class RespuestaDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PdfImpresionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoErrorField, value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoDocumento {
            get {
                return this.EstadoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoDocumentoField, value) != true)) {
                    this.EstadoDocumentoField = value;
                    this.RaisePropertyChanged("EstadoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PdfImpresion {
            get {
                return this.PdfImpresionField;
            }
            set {
                if ((object.ReferenceEquals(this.PdfImpresionField, value) != true)) {
                    this.PdfImpresionField = value;
                    this.RaisePropertyChanged("PdfImpresion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLEnvio {
            get {
                return this.XMLEnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLEnvioField, value) != true)) {
                    this.XMLEnvioField = value;
                    this.RaisePropertyChanged("XMLEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLRespuesta {
            get {
                return this.XMLRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLRespuestaField, value) != true)) {
                    this.XMLRespuestaField = value;
                    this.RaisePropertyChanged("XMLRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/ServicioImpresion")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FooterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImpresoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Footer {
            get {
                return this.FooterField;
            }
            set {
                if ((object.ReferenceEquals(this.FooterField, value) != true)) {
                    this.FooterField = value;
                    this.RaisePropertyChanged("Footer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impresora {
            get {
                return this.ImpresoraField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpresoraField, value) != true)) {
                    this.ImpresoraField = value;
                    this.RaisePropertyChanged("Impresora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QR {
            get {
                return this.QRField;
            }
            set {
                if ((object.ReferenceEquals(this.QRField, value) != true)) {
                    this.QRField = value;
                    this.RaisePropertyChanged("QR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sonido {
            get {
                return this.SonidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SonidoField, value) != true)) {
                    this.SonidoField = value;
                    this.RaisePropertyChanged("Sonido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ticket {
            get {
                return this.TicketField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketField, value) != true)) {
                    this.TicketField = value;
                    this.RaisePropertyChanged("Ticket");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicioImpresionPedido.IDocumentoPedido")]
    public interface IDocumentoPedido {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/EstadoDocumento", ReplyAction="http://tempuri.org/IDocumentoPedido/EstadoDocumentoResponse")]
        TwoTecnology.WebVentas.servicioImpresionPedido.RespuestaDocumento EstadoDocumento(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/EstadoDocumento", ReplyAction="http://tempuri.org/IDocumentoPedido/EstadoDocumentoResponse")]
        System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioImpresionPedido.RespuestaDocumento> EstadoDocumentoAsync(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/Existe", ReplyAction="http://tempuri.org/IDocumentoPedido/ExisteResponse")]
        bool Existe(string Ruc, string Local);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/Existe", ReplyAction="http://tempuri.org/IDocumentoPedido/ExisteResponse")]
        System.Threading.Tasks.Task<bool> ExisteAsync(string Ruc, string Local);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/ExistsWithKey", ReplyAction="http://tempuri.org/IDocumentoPedido/ExistsWithKeyResponse")]
        bool ExistsWithKey(string Ruc, string Local, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/ExistsWithKey", ReplyAction="http://tempuri.org/IDocumentoPedido/ExistsWithKeyResponse")]
        System.Threading.Tasks.Task<bool> ExistsWithKeyAsync(string Ruc, string Local, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/Obtener", ReplyAction="http://tempuri.org/IDocumentoPedido/ObtenerResponse")]
        TwoTecnology.WebVentas.servicioImpresionPedido.Pedido Obtener(string Ruc, string Local, string columnas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/Obtener", ReplyAction="http://tempuri.org/IDocumentoPedido/ObtenerResponse")]
        System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioImpresionPedido.Pedido> ObtenerAsync(string Ruc, string Local, string columnas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/ObtenerByCodigo", ReplyAction="http://tempuri.org/IDocumentoPedido/ObtenerByCodigoResponse")]
        TwoTecnology.WebVentas.servicioImpresionPedido.Pedido ObtenerByCodigo(string Codigo, string columnas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/ObtenerByCodigo", ReplyAction="http://tempuri.org/IDocumentoPedido/ObtenerByCodigoResponse")]
        System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioImpresionPedido.Pedido> ObtenerByCodigoAsync(string Codigo, string columnas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/ObtenerTextoByCodigo", ReplyAction="http://tempuri.org/IDocumentoPedido/ObtenerTextoByCodigoResponse")]
        string ObtenerTextoByCodigo(string Codigo, string columnas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/ObtenerTextoByCodigo", ReplyAction="http://tempuri.org/IDocumentoPedido/ObtenerTextoByCodigoResponse")]
        System.Threading.Tasks.Task<string> ObtenerTextoByCodigoAsync(string Codigo, string columnas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/Actualizar", ReplyAction="http://tempuri.org/IDocumentoPedido/ActualizarResponse")]
        void Actualizar(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/Actualizar", ReplyAction="http://tempuri.org/IDocumentoPedido/ActualizarResponse")]
        System.Threading.Tasks.Task ActualizarAsync(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/ObtenerPdfA4", ReplyAction="http://tempuri.org/IDocumentoPedido/ObtenerPdfA4Response")]
        string ObtenerPdfA4(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/ObtenerPdfA4", ReplyAction="http://tempuri.org/IDocumentoPedido/ObtenerPdfA4Response")]
        System.Threading.Tasks.Task<string> ObtenerPdfA4Async(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/ObtenerPdf58", ReplyAction="http://tempuri.org/IDocumentoPedido/ObtenerPdf58Response")]
        string ObtenerPdf58(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/ObtenerPdf58", ReplyAction="http://tempuri.org/IDocumentoPedido/ObtenerPdf58Response")]
        System.Threading.Tasks.Task<string> ObtenerPdf58Async(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/ObtenerPdf80", ReplyAction="http://tempuri.org/IDocumentoPedido/ObtenerPdf80Response")]
        string ObtenerPdf80(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPedido/ObtenerPdf80", ReplyAction="http://tempuri.org/IDocumentoPedido/ObtenerPdf80Response")]
        System.Threading.Tasks.Task<string> ObtenerPdf80Async(string Ruc, string Tipo, string Serie, string Correlativo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentoPedidoChannel : TwoTecnology.WebVentas.servicioImpresionPedido.IDocumentoPedido, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentoPedidoClient : System.ServiceModel.ClientBase<TwoTecnology.WebVentas.servicioImpresionPedido.IDocumentoPedido>, TwoTecnology.WebVentas.servicioImpresionPedido.IDocumentoPedido {
        
        public DocumentoPedidoClient() {
        }
        
        public DocumentoPedidoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentoPedidoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentoPedidoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentoPedidoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TwoTecnology.WebVentas.servicioImpresionPedido.RespuestaDocumento EstadoDocumento(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.EstadoDocumento(Ruc, Tipo, Serie, Correlativo);
        }
        
        public System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioImpresionPedido.RespuestaDocumento> EstadoDocumentoAsync(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.EstadoDocumentoAsync(Ruc, Tipo, Serie, Correlativo);
        }
        
        public bool Existe(string Ruc, string Local) {
            return base.Channel.Existe(Ruc, Local);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteAsync(string Ruc, string Local) {
            return base.Channel.ExisteAsync(Ruc, Local);
        }
        
        public bool ExistsWithKey(string Ruc, string Local, string clave) {
            return base.Channel.ExistsWithKey(Ruc, Local, clave);
        }
        
        public System.Threading.Tasks.Task<bool> ExistsWithKeyAsync(string Ruc, string Local, string clave) {
            return base.Channel.ExistsWithKeyAsync(Ruc, Local, clave);
        }
        
        public TwoTecnology.WebVentas.servicioImpresionPedido.Pedido Obtener(string Ruc, string Local, string columnas) {
            return base.Channel.Obtener(Ruc, Local, columnas);
        }
        
        public System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioImpresionPedido.Pedido> ObtenerAsync(string Ruc, string Local, string columnas) {
            return base.Channel.ObtenerAsync(Ruc, Local, columnas);
        }
        
        public TwoTecnology.WebVentas.servicioImpresionPedido.Pedido ObtenerByCodigo(string Codigo, string columnas) {
            return base.Channel.ObtenerByCodigo(Codigo, columnas);
        }
        
        public System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioImpresionPedido.Pedido> ObtenerByCodigoAsync(string Codigo, string columnas) {
            return base.Channel.ObtenerByCodigoAsync(Codigo, columnas);
        }
        
        public string ObtenerTextoByCodigo(string Codigo, string columnas) {
            return base.Channel.ObtenerTextoByCodigo(Codigo, columnas);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerTextoByCodigoAsync(string Codigo, string columnas) {
            return base.Channel.ObtenerTextoByCodigoAsync(Codigo, columnas);
        }
        
        public void Actualizar(string Codigo) {
            base.Channel.Actualizar(Codigo);
        }
        
        public System.Threading.Tasks.Task ActualizarAsync(string Codigo) {
            return base.Channel.ActualizarAsync(Codigo);
        }
        
        public string ObtenerPdfA4(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.ObtenerPdfA4(Ruc, Tipo, Serie, Correlativo);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerPdfA4Async(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.ObtenerPdfA4Async(Ruc, Tipo, Serie, Correlativo);
        }
        
        public string ObtenerPdf58(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.ObtenerPdf58(Ruc, Tipo, Serie, Correlativo);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerPdf58Async(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.ObtenerPdf58Async(Ruc, Tipo, Serie, Correlativo);
        }
        
        public string ObtenerPdf80(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.ObtenerPdf80(Ruc, Tipo, Serie, Correlativo);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerPdf80Async(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.ObtenerPdf80Async(Ruc, Tipo, Serie, Correlativo);
        }
    }
}
