//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoTecnology.WebVentas.servicioDocumento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaDocumento", Namespace="http://schemas.datacontract.org/2004/07/TwoTecnology.ServicioDocumentos")]
    [System.SerializableAttribute()]
    public partial class RespuestaDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PdfImpresionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PdfImpresionBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLEnvioBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLRespuestaBaseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoErrorField, value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoDocumento {
            get {
                return this.EstadoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoDocumentoField, value) != true)) {
                    this.EstadoDocumentoField = value;
                    this.RaisePropertyChanged("EstadoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PdfImpresion {
            get {
                return this.PdfImpresionField;
            }
            set {
                if ((object.ReferenceEquals(this.PdfImpresionField, value) != true)) {
                    this.PdfImpresionField = value;
                    this.RaisePropertyChanged("PdfImpresion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PdfImpresionBase {
            get {
                return this.PdfImpresionBaseField;
            }
            set {
                if ((object.ReferenceEquals(this.PdfImpresionBaseField, value) != true)) {
                    this.PdfImpresionBaseField = value;
                    this.RaisePropertyChanged("PdfImpresionBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLEnvio {
            get {
                return this.XMLEnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLEnvioField, value) != true)) {
                    this.XMLEnvioField = value;
                    this.RaisePropertyChanged("XMLEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLEnvioBase {
            get {
                return this.XMLEnvioBaseField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLEnvioBaseField, value) != true)) {
                    this.XMLEnvioBaseField = value;
                    this.RaisePropertyChanged("XMLEnvioBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLRespuesta {
            get {
                return this.XMLRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLRespuestaField, value) != true)) {
                    this.XMLRespuestaField = value;
                    this.RaisePropertyChanged("XMLRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLRespuestaBase {
            get {
                return this.XMLRespuestaBaseField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLRespuestaBaseField, value) != true)) {
                    this.XMLRespuestaBaseField = value;
                    this.RaisePropertyChanged("XMLRespuestaBase");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImpresionDocumento", Namespace="http://schemas.datacontract.org/2004/07/TwoTecnology.ServicioDocumentos")]
    [System.SerializableAttribute()]
    public partial class ImpresionDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FooterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Footer {
            get {
                return this.FooterField;
            }
            set {
                if ((object.ReferenceEquals(this.FooterField, value) != true)) {
                    this.FooterField = value;
                    this.RaisePropertyChanged("Footer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QR {
            get {
                return this.QRField;
            }
            set {
                if ((object.ReferenceEquals(this.QRField, value) != true)) {
                    this.QRField = value;
                    this.RaisePropertyChanged("QR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ticket {
            get {
                return this.TicketField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketField, value) != true)) {
                    this.TicketField = value;
                    this.RaisePropertyChanged("Ticket");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicioDocumento.IDocumento")]
    public interface IDocumento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/EnvioDocumento", ReplyAction="http://tempuri.org/IDocumento/EnvioDocumentoResponse")]
        int EnvioDocumento(string Ruc, string Tipo, string Serie, string Correlativo, byte[] Documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/EnvioDocumento", ReplyAction="http://tempuri.org/IDocumento/EnvioDocumentoResponse")]
        System.Threading.Tasks.Task<int> EnvioDocumentoAsync(string Ruc, string Tipo, string Serie, string Correlativo, byte[] Documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/EstadoDocumento", ReplyAction="http://tempuri.org/IDocumento/EstadoDocumentoResponse")]
        TwoTecnology.WebVentas.servicioDocumento.RespuestaDocumento EstadoDocumento(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/EstadoDocumento", ReplyAction="http://tempuri.org/IDocumento/EstadoDocumentoResponse")]
        System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioDocumento.RespuestaDocumento> EstadoDocumentoAsync(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/ObtenerPdf", ReplyAction="http://tempuri.org/IDocumento/ObtenerPdfResponse")]
        string ObtenerPdf(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/ObtenerPdf", ReplyAction="http://tempuri.org/IDocumento/ObtenerPdfResponse")]
        System.Threading.Tasks.Task<string> ObtenerPdfAsync(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/ObtenerXml", ReplyAction="http://tempuri.org/IDocumento/ObtenerXmlResponse")]
        string ObtenerXml(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/ObtenerXml", ReplyAction="http://tempuri.org/IDocumento/ObtenerXmlResponse")]
        System.Threading.Tasks.Task<string> ObtenerXmlAsync(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/ObtenerZip", ReplyAction="http://tempuri.org/IDocumento/ObtenerZipResponse")]
        string ObtenerZip(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/ObtenerZip", ReplyAction="http://tempuri.org/IDocumento/ObtenerZipResponse")]
        System.Threading.Tasks.Task<string> ObtenerZipAsync(string Ruc, string Tipo, string Serie, string Correlativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/IsObtenerImpresion", ReplyAction="http://tempuri.org/IDocumento/IsObtenerImpresionResponse")]
        bool IsObtenerImpresion(string Ruc, string Serie, string Impresora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/IsObtenerImpresion", ReplyAction="http://tempuri.org/IDocumento/IsObtenerImpresionResponse")]
        System.Threading.Tasks.Task<bool> IsObtenerImpresionAsync(string Ruc, string Serie, string Impresora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/ObtenerImpresion", ReplyAction="http://tempuri.org/IDocumento/ObtenerImpresionResponse")]
        TwoTecnology.WebVentas.servicioDocumento.ImpresionDocumento ObtenerImpresion(string Ruc, string Serie, string Impresora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/ObtenerImpresion", ReplyAction="http://tempuri.org/IDocumento/ObtenerImpresionResponse")]
        System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioDocumento.ImpresionDocumento> ObtenerImpresionAsync(string Ruc, string Serie, string Impresora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/ObtenerImpresionByCodigo", ReplyAction="http://tempuri.org/IDocumento/ObtenerImpresionByCodigoResponse")]
        TwoTecnology.WebVentas.servicioDocumento.ImpresionDocumento ObtenerImpresionByCodigo(string Ruc, string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/ObtenerImpresionByCodigo", ReplyAction="http://tempuri.org/IDocumento/ObtenerImpresionByCodigoResponse")]
        System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioDocumento.ImpresionDocumento> ObtenerImpresionByCodigoAsync(string Ruc, string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/ActualizarImpresion", ReplyAction="http://tempuri.org/IDocumento/ActualizarImpresionResponse")]
        void ActualizarImpresion(string Ruc, string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumento/ActualizarImpresion", ReplyAction="http://tempuri.org/IDocumento/ActualizarImpresionResponse")]
        System.Threading.Tasks.Task ActualizarImpresionAsync(string Ruc, string Codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentoChannel : TwoTecnology.WebVentas.servicioDocumento.IDocumento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentoClient : System.ServiceModel.ClientBase<TwoTecnology.WebVentas.servicioDocumento.IDocumento>, TwoTecnology.WebVentas.servicioDocumento.IDocumento {
        
        public DocumentoClient() {
        }
        
        public DocumentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int EnvioDocumento(string Ruc, string Tipo, string Serie, string Correlativo, byte[] Documento) {
            return base.Channel.EnvioDocumento(Ruc, Tipo, Serie, Correlativo, Documento);
        }
        
        public System.Threading.Tasks.Task<int> EnvioDocumentoAsync(string Ruc, string Tipo, string Serie, string Correlativo, byte[] Documento) {
            return base.Channel.EnvioDocumentoAsync(Ruc, Tipo, Serie, Correlativo, Documento);
        }
        
        public TwoTecnology.WebVentas.servicioDocumento.RespuestaDocumento EstadoDocumento(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.EstadoDocumento(Ruc, Tipo, Serie, Correlativo);
        }
        
        public System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioDocumento.RespuestaDocumento> EstadoDocumentoAsync(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.EstadoDocumentoAsync(Ruc, Tipo, Serie, Correlativo);
        }
        
        public string ObtenerPdf(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.ObtenerPdf(Ruc, Tipo, Serie, Correlativo);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerPdfAsync(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.ObtenerPdfAsync(Ruc, Tipo, Serie, Correlativo);
        }
        
        public string ObtenerXml(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.ObtenerXml(Ruc, Tipo, Serie, Correlativo);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerXmlAsync(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.ObtenerXmlAsync(Ruc, Tipo, Serie, Correlativo);
        }
        
        public string ObtenerZip(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.ObtenerZip(Ruc, Tipo, Serie, Correlativo);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerZipAsync(string Ruc, string Tipo, string Serie, string Correlativo) {
            return base.Channel.ObtenerZipAsync(Ruc, Tipo, Serie, Correlativo);
        }
        
        public bool IsObtenerImpresion(string Ruc, string Serie, string Impresora) {
            return base.Channel.IsObtenerImpresion(Ruc, Serie, Impresora);
        }
        
        public System.Threading.Tasks.Task<bool> IsObtenerImpresionAsync(string Ruc, string Serie, string Impresora) {
            return base.Channel.IsObtenerImpresionAsync(Ruc, Serie, Impresora);
        }
        
        public TwoTecnology.WebVentas.servicioDocumento.ImpresionDocumento ObtenerImpresion(string Ruc, string Serie, string Impresora) {
            return base.Channel.ObtenerImpresion(Ruc, Serie, Impresora);
        }
        
        public System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioDocumento.ImpresionDocumento> ObtenerImpresionAsync(string Ruc, string Serie, string Impresora) {
            return base.Channel.ObtenerImpresionAsync(Ruc, Serie, Impresora);
        }
        
        public TwoTecnology.WebVentas.servicioDocumento.ImpresionDocumento ObtenerImpresionByCodigo(string Ruc, string Codigo) {
            return base.Channel.ObtenerImpresionByCodigo(Ruc, Codigo);
        }
        
        public System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioDocumento.ImpresionDocumento> ObtenerImpresionByCodigoAsync(string Ruc, string Codigo) {
            return base.Channel.ObtenerImpresionByCodigoAsync(Ruc, Codigo);
        }
        
        public void ActualizarImpresion(string Ruc, string Codigo) {
            base.Channel.ActualizarImpresion(Ruc, Codigo);
        }
        
        public System.Threading.Tasks.Task ActualizarImpresionAsync(string Ruc, string Codigo) {
            return base.Channel.ActualizarImpresionAsync(Ruc, Codigo);
        }
    }
}
