//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoTecnology.WebVentas.servicioImpresionPrecuenta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Precuenta", Namespace="http://schemas.datacontract.org/2004/07/ServicioImpresion")]
    [System.SerializableAttribute()]
    public partial class Precuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FooterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImpresoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Footer {
            get {
                return this.FooterField;
            }
            set {
                if ((object.ReferenceEquals(this.FooterField, value) != true)) {
                    this.FooterField = value;
                    this.RaisePropertyChanged("Footer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impresora {
            get {
                return this.ImpresoraField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpresoraField, value) != true)) {
                    this.ImpresoraField = value;
                    this.RaisePropertyChanged("Impresora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QR {
            get {
                return this.QRField;
            }
            set {
                if ((object.ReferenceEquals(this.QRField, value) != true)) {
                    this.QRField = value;
                    this.RaisePropertyChanged("QR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ticket {
            get {
                return this.TicketField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketField, value) != true)) {
                    this.TicketField = value;
                    this.RaisePropertyChanged("Ticket");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicioImpresionPrecuenta.IDocumentoPrecuenta")]
    public interface IDocumentoPrecuenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPrecuenta/Existe", ReplyAction="http://tempuri.org/IDocumentoPrecuenta/ExisteResponse")]
        bool Existe(string Ruc, string Local);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPrecuenta/Existe", ReplyAction="http://tempuri.org/IDocumentoPrecuenta/ExisteResponse")]
        System.Threading.Tasks.Task<bool> ExisteAsync(string Ruc, string Local);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPrecuenta/Obtener", ReplyAction="http://tempuri.org/IDocumentoPrecuenta/ObtenerResponse")]
        TwoTecnology.WebVentas.servicioImpresionPrecuenta.Precuenta Obtener(string Ruc, string Local);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPrecuenta/Obtener", ReplyAction="http://tempuri.org/IDocumentoPrecuenta/ObtenerResponse")]
        System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioImpresionPrecuenta.Precuenta> ObtenerAsync(string Ruc, string Local);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPrecuenta/ObtenerByCodigo", ReplyAction="http://tempuri.org/IDocumentoPrecuenta/ObtenerByCodigoResponse")]
        TwoTecnology.WebVentas.servicioImpresionPrecuenta.Precuenta ObtenerByCodigo(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPrecuenta/ObtenerByCodigo", ReplyAction="http://tempuri.org/IDocumentoPrecuenta/ObtenerByCodigoResponse")]
        System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioImpresionPrecuenta.Precuenta> ObtenerByCodigoAsync(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPrecuenta/Actualizar", ReplyAction="http://tempuri.org/IDocumentoPrecuenta/ActualizarResponse")]
        void Actualizar(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentoPrecuenta/Actualizar", ReplyAction="http://tempuri.org/IDocumentoPrecuenta/ActualizarResponse")]
        System.Threading.Tasks.Task ActualizarAsync(string Codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentoPrecuentaChannel : TwoTecnology.WebVentas.servicioImpresionPrecuenta.IDocumentoPrecuenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentoPrecuentaClient : System.ServiceModel.ClientBase<TwoTecnology.WebVentas.servicioImpresionPrecuenta.IDocumentoPrecuenta>, TwoTecnology.WebVentas.servicioImpresionPrecuenta.IDocumentoPrecuenta {
        
        public DocumentoPrecuentaClient() {
        }
        
        public DocumentoPrecuentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentoPrecuentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentoPrecuentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentoPrecuentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Existe(string Ruc, string Local) {
            return base.Channel.Existe(Ruc, Local);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteAsync(string Ruc, string Local) {
            return base.Channel.ExisteAsync(Ruc, Local);
        }
        
        public TwoTecnology.WebVentas.servicioImpresionPrecuenta.Precuenta Obtener(string Ruc, string Local) {
            return base.Channel.Obtener(Ruc, Local);
        }
        
        public System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioImpresionPrecuenta.Precuenta> ObtenerAsync(string Ruc, string Local) {
            return base.Channel.ObtenerAsync(Ruc, Local);
        }
        
        public TwoTecnology.WebVentas.servicioImpresionPrecuenta.Precuenta ObtenerByCodigo(string Codigo) {
            return base.Channel.ObtenerByCodigo(Codigo);
        }
        
        public System.Threading.Tasks.Task<TwoTecnology.WebVentas.servicioImpresionPrecuenta.Precuenta> ObtenerByCodigoAsync(string Codigo) {
            return base.Channel.ObtenerByCodigoAsync(Codigo);
        }
        
        public void Actualizar(string Codigo) {
            base.Channel.Actualizar(Codigo);
        }
        
        public System.Threading.Tasks.Task ActualizarAsync(string Codigo) {
            return base.Channel.ActualizarAsync(Codigo);
        }
    }
}
